default_platform(:ios)

platform :ios do
  desc "Сборка и экспорт IPA файла"
  lane :build_app do
    clear_derived_data # Очистка производных данных
    cocoapods # Установка зависимостей

    gym( # Сборка IPA
      workspace: "PasscodeView.xcworkspace",
      scheme: "PasscodeView",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "ReleaseApp.app"
    )
  end
end
